-- 创建客户表
CREATE TABLE IF NOT EXISTS customers (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  primary_channel VARCHAR(50) NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(50) UNIQUE,
  wechat_openid VARCHAR(255) UNIQUE,
  whatsapp_id VARCHAR(255) UNIQUE,
  line_id VARCHAR(255) UNIQUE,
  telegram_id VARCHAR(255) UNIQUE,
  facebook_id VARCHAR(255) UNIQUE,
  avatar_url VARCHAR(500),
  location VARCHAR(255),
  notes TEXT,
  tags JSON,
  custom_fields JSON,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_interaction_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by CHAR(36),
  updated_by CHAR(36),
  INDEX idx_primary_channel (primary_channel),
  INDEX idx_email (email),
  INDEX idx_phone (phone),
  INDEX idx_active (active),
  INDEX idx_last_interaction (last_interaction_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
